services:
  ollama:
    image: docker.io/ollama/ollama:0.1.16
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - continue
  webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    ports:
      - 11001:8080
    depends_on:
      - ollama
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    networks:
      - continue
  continue:
    build: .
    ports:
      - 65432:65432
    depends_on:
      - ollama
    networks:
      - continue

volumes:
  ollama:

networks:
  continue: